console.log(`typeof 1: ${typeof 1}`)
console.log(`typeof NaN: ${typeof NaN}`)
console.log(`typeof '1': ${typeof '1'}`)
console.log(`typeof true: ${typeof true}`)
console.log(`typeof undefined: ${typeof undefined}`)
console.log(`typeof unused identifier: ${typeof x}`)
console.log(`typeof Symbol(): ${typeof Symbol()}`)
console.log(`typeof Symbol(1): ${typeof Symbol(1)}`)
console.log(`typeof Symbol('1'): ${typeof Symbol('1')}`)
console.log(`typeof null: ${typeof null}`)
console.log(`typeof {}: ${typeof {}}`)
console.log(`typeof new Date(): ${typeof new Date()}`)
console.log(`typeof () => {}: ${typeof (() => {})}`)